### ISSUE TITLE
Action space

### ISSUE THREAD

**Issue by Velodromo** [MartinEnevig/astroClock#12]
Jeg foreslår følgende action space:

 * Afstand planeten rykkes 0-150mm:  Box
 * Retning planeten rykkes (forskel i polar radius) : Box

**Comment by MartinEnevig** [comment]
Det er best practice at normalisere sit action space - har jeg læst. Så jeg foreslår, at action space skal være to boxes med lower bound 0 og upper bound 1, og så skal vi have en funktion, der oversætter det til afstand og retning, som kan bruges til at opdatere observation space - og i sidste ende til at sende til robot-armen.

Vi skal i øvrigt tænke os lidt om, hvordan vi sikrer, at agenten ikke kan tage actions, der flytter rikken uden for observation space. Så den f.eks. ikke forsøger at sende den ud over kanten. Det er ikke nok bare at straffe det i reward, for env crasher, hvis vi forsøger at opdatere observation space med en værdi, der ligger uden for. Så vi skal have en funktion, der clipper action, hvis det vil føre til en observation uden for skiven.

**Comment by Velodromo** [comment]
Aha, det er fint for mig at køre med normaliseret action space. 
Tænkte bare, at det måske ville resultere i unødig ekstra beregning, hvis gym først skal omregne til normaliseret output, hvorefter vi efterfølgende omregner til egentlige værdier. Men lad os gøre det, hvis du har læst at det er mest korrekt. Det betyder nok ikke super meget for performance.

Ja, der er vel flere metoder til at sørge for at observation space ikke overskrides:
1. Vi kan lave observation space større end nødvendigt så den godt kan køre udenfor, men bliver straffet (hårdt) hvis den gør det.
2. Vi kan clippe action eller observation space så vi ikke bevæger os udenfor.
3. Vi kan lade den dø, hvis den bevæger sig udenfor og lave en reset(). Ligesom når pælen vælter i eksemplet, hvor den skal forsøge at balancere pælen.

Jeg hælder nok mest til metode 3.
Metode 1 tror jeg ikke er optimal, da den i praksis ikke må bevæge sig udenfor pladen.
Samme problemstilling er relevant i forbindelse med kollision. Skal vi så forsætte eller genstarte? 

God idé at benytte env_checker. Måske vi skal kigge på det sammen når jeg har det grundlæggende klar.
